int add1(int a, int b) { call by value
    a += 1;
    b += 1;
    return a+b;
}

int add2(int &a, int &b) { call by reference
    a += 1;
    b += 1;
    return a+b;
}

a = 4, b = 5;

add1(a,b) = 11
console.log a = 4
console.log b = 5

add2(a,b) = 11
console.log a = 5
console.log b = 6


=  assignment 대입 연산자

callback 메모리에서 호출 런타임관련

인스턴스화되면 내 눈에 보이지않는 크롬 메모리에 할당됐다

this 메모리에 인스턴시에이싱된 인스턴스 자신
클래스가 메모리에 객체화된 자신

크리에이트서버한 스레드한테 try catch가 있고 거기에 error를 throw한것이다